name: Tender Scraper

on:
  schedule:
    - cron: '* * * * *'   # run every day
  workflow_dispatch: {}      # allow manual trigger from Actions tab

permissions:
  contents: write   # allow workflow to commit JSON updates back to repo

concurrency:
  group: "tender-scraper-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # needed to push commits

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tender scraper
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          python scrape_tenders.py

      - name: Commit updated tenders file (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add all_tenders_data.json || true

          if ! git diff --cached --quiet; then
            git commit -m "Update tenders data [skip ci]" || echo "Nothing to commit"
            git push
          else
            echo "No changes to commit."
          fi
